### PR TITLE
updated ID

### PR DESCRIPTION
**Pull request by thea-m**
https://github.com/BetaMasaheft/Documentation/issues/1672

### CODE REVIEW

**Review by DenisNosnitsin1970 — APPROVED** [review]

**Comment by Ralph-Lee-UK** [comment]
@thea-m I don't currently see LIT6351HymnLalibala in works. Did you create this as the work file for the short hymn to Lalibela that we discussed before? Where might I find it?

**Comment by DenisNosnitsin1970** [comment]
It is there.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 @thea-m LIT6351HymnLalibala is in the branch https://github.com/BetaMasaheft/Works/tree/DR_21_01_Lalibala/new
but not in the main branch, which is why I think I haven't seen it. How do we put this right?

**Comment by thea-m** [comment]
The PR correctly linked to by @Ralph-Lee-UK has simply not yet been merged. As soon as it will be, the ID will be ready and available!

**Pull request merged**
