### PR TITLE
Vitagrazia 3

### PR DESCRIPTION
**Pull request by vitagrazia81**
Cara Dorothea, 
sorry again. It is still me with this description :-) I follow your suggestion creating a new branch. 
Now I think the corrections and additional encoding (Miniatures and Ornamental bands) are visible. I checked online and I have seen that there are something which I need to change, e.g: it is written: "Original binding: yes", but actually it is not. What should I change it?
Thank you again, Dorothea.

### CODE REVIEW

**Comment by vitagrazia81** [comment]
And online, in the incipit of the miracles I see strange things: like in the parenthesis for the language of the text, nothing there.

**Comment by thea-m** [comment]
Don't worry, this is nothing, we have Pull Requests that go on for months (mostly from me...)!
Now, there was a bit of branch chaos, as could be expected. Could you maybe solve the conflicts that are now present in this PR? (They are mostly the new locus changes, but I think it's better if you do it, because you know the description better and know which version is the most current one).
For the binding: in `<binding>`, there is currently `<binding contemporary="true" xml:id="binding">`. If the binding is not contemporary, simply change "true" to "false".
The language is not given in the online view because, even though you added it in the msItems and incipits, you did not define it in the element `<langUsage>` at the end of the file (it currently only contains English). All languages used in the file must be defined there, so in this case you need to add `<language ident="gez">Gǝʿǝz</language>`. 
I hope that helps! Please always tell us if you notice something else that's strange!

**Comment by vitagrazia81** [comment]
Dear Dorothea, you are always very clear and patient.  thank you. I have followed your instructions. I hope now it is fine.

**Comment by thea-m** [comment]
Thank you! I see that the locus is added, but the binding and langUsage changes haven't been carried out yet - maybe you committed them but didn't push?

**Comment by vitagrazia81** [comment]
Dear Dorothea, 
thank you. I hope now they are visible.

**Review by thea-m — APPROVED** [review]

**Comment by thea-m** [comment]
Yes, now they're there! I'm just re-adding the link to the images, which maybe got lost with all these versions, and then I'll merge. Don't worry, it won't always take so many steps, but it is completely normal in the beginning!

**Comment by vitagrazia81** [comment]
Thank you very much Dorothea, for all :-).. I am really grateful! 
Un caro saluto, 
Vita

**Pull request merged**
