### PR TITLE
De ethiop1correction

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
minor changes

### CODE REVIEW

**Comment by thea-m** [comment]
It seems that there were too many merges here. No there are no changes visible anymore. 
If you look through the commit history, can you remember which ones were the significant changes, then we can reconstruct them?

**Comment by DenisNosnitsin1970** [comment]
There are a few slight changes, nothing big. I think it is better to merge and I will look though. No idea how the ygot stuck.

**Comment by thea-m** [comment]
If I understand it correctly, if we merge now, there will be no changes, because none are visible anymore.

**Comment by thea-m** [comment]
image

**Comment by DenisNosnitsin1970** [comment]
Ok, let it be merged.

**Comment by thea-m** [comment]
:(

**Pull request closed without merging**
