### PR TITLE
Ds ethiop10 dn

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**

### CODE REVIEW

**Comment by DenisNosnitsin1970** [comment]
Sorry, I mistakenly sent the record into false branch. I assume it cannot be discarded, cant it? Should it be merged, and should I make the same changes in the record in the correct branch?

**Comment by thea-m** [comment]
The changes seem fine to me. You probably reactivated an old branch which led to a lot of merging, but whether that branch is called 10 or 11 is irrelevant. Are the changes visible here the ones that you want to have?

**Comment by thea-m** [comment]
image

**Comment by DenisNosnitsin1970** [comment]
Yes, they are.

**Comment by thea-m** [comment]
Then it should be fine.

**Pull request merged**
