### PR TITLE
Bruce 88

### PR DESCRIPTION
**Pull request by thea-m**
The moment of truth :)

### CODE REVIEW

**Comment by DariaElagina** [comment]
Do they have scales there? :) I see no problems, but let's wait for Denis :)

**Comment by DenisNosnitsin1970** [comment]
What are scales?

**Comment by thea-m** [comment]
I have my kitchen scale!

**Comment by DenisNosnitsin1970** [comment]
Oh!

**Comment by DariaElagina** [comment]
@DenisNosnitsin1970 Waage :) @thea-m you are extremly good prepared :)

**Comment by DenisNosnitsin1970** [comment]
Do not show to the Bodleianers, they will be jelous.

**Comment by DenisNosnitsin1970** [comment]
:)

**Comment by thea-m** [comment]
They do supposedly have scales somewhere. Leiden University Library weighs all manuscripts before handing them out and when they are returned, as a preventive measure. But this makes more sense for paper manuscripts, with parchment a few grams variation can be attributed as much to humidity as to suspicious acts.

**Pull request merged**
