### PR TITLE
BLadd18994

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
Excellent idea! Would you suggest an ID for this particular version (including the New Testament readings, or a general "Psalter that does not follow the common arrangement" ID? Since I do not yet know the tradition well, I would tend towards the latter, which would ease the encoding.

**Comment by DenisNosnitsin1970** [comment]
As a practical temporary solution, we can have a summary ID for peculiar Psalter versions (they all seem to be linked to Horologium, in one way or another). But two versions can get IDs now, or as soon as we have encountered witnesses: the Psalter without Anqasa berhan at the end, and Psalter with other texts distributed between the psalms (like Mazmura Krestos in DD-050).

**Comment by thea-m** [comment]
Very good! So for "Psalter without Anqasa berhan" you mean with Weddase Maryam, but without Anqasa berhan? Just to be sure.

**Comment by DenisNosnitsin1970** [comment]
Yes, just the last one, Anqasa berhan, is missing.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 is it ok like this? It's just one non-traditional Psalter ID now, we can create others in the future

**Comment by thea-m** [comment]
Sure, it is in the manuscript description in the record. Thank you!

**Pull request merged**
