### PR TITLE
Dr 22 03 golden gospel

### PR DESCRIPTION
**Pull request by thea-m**
Reverting Golden Gospel of Dabra Libānos commits
Sorry, @eu-genia , this file is very special and has been encoded with a lot particularities (also described in the new article). For now, the visualisation problem is secondary, @nafisa-valieva will let you know when she will have time to discuss it, but for now, it's better to leave it like this and preserve the encoding as it is. Thank you! It must have been a lot of work already figuring the problems out.

### CODE REVIEW

**Comment by thea-m** [comment]
For sure, it is important and the analysis is correct, but it cannot be dealt with right now, it simply has to wait a bit. I understand that this might be frustrating.

**Comment by eu-genia** [comment]
the string in the code (viewItem)
`                string-join(distinct-values(($TEI//t:editor[@key = $resp]/text() | $TEI//t:respStmt[@xml:id = $resp]/t:name/text())), ', ')
`
says that the resp inside of respStmt is taken as `xml:id`. This is why there may not be multiple `resp `elements. I suggest that at least this is corrected in the data and not in the code.

**Review by nafisa-valieva — APPROVED** [review]
Dear Eugenia, this seems to be fine! thank you!

**Comment by nafisa-valieva** [comment]
Dear @eu-genia, dear @thea-m,
thank you very much for the corrections! Because we had discussed a lot with Pietro, I fear to loose any bit of our success. To be able to decide upon bigger changes, I need to immerse in this work and I can't do it for the moment.

**Pull request merged**
