### PR TITLE
EMIP Tweed Scrolls Edits to EMIPms00469

### PR DESCRIPTION
**Pull request by Ralph-Lee-UK**
Edits to text formatting to check whether text appears correctly formatted on BM (the previous file was copied from the wrong place - this one should be correct!)

### CODE REVIEW

**Comment by eu-genia** [comment]
updated. 

you could have pushed the new file to the same branch/pull request as here https://github.com/BetaMasaheft/Manuscripts/pull/2409; since you have created this one I have closed the previous PR without merging

if more changes to this MS come let us stay in the May 6 branch here, thank you!

**Comment by Ralph-Lee-UK** [comment]
@eu-genia I have just pushed another manual edit of the text file to this branch. If I am not making a pull request, should I just message you like this?

**Comment by eu-genia** [comment]
you do not need to message, I am notified of new pushes ) updated

**Comment by eu-genia** [comment]
updated online

**Comment by eu-genia** [comment]
reupdated

**Comment by Ralph-Lee-UK** [comment]
@eu-genia back on this after a long time away. I am trying a different strategy this time - as the formatting is still not correct.

**Comment by eu-genia** [comment]
updated.
note that there are references to works from msItems `ms_i1 `and `ms_i3 `that do not exist and cause errors (`LIT4307Prayer `and `LIT58888AsmatPrayer`)

**Review by eu-genia — APPROVED** [review]

**Comment by Ralph-Lee-UK** [comment]
@eu-genia not all the files have updated correctly - does it take a little time sometimes?

**Comment by Ralph-Lee-UK** [comment]
@eu-genia now there is an error message when the files are accessed. Let me know if there is something to put right!

**Comment by Ralph-Lee-UK** [comment]
@eu-genia it seems that there a duplicate files. I am not sure what to do to resolve this.

**Comment by eu-genia** [comment]
this is a known issue, https://github.com/BetaMasaheft/Documentation/issues/1955 
for the moment I can only delete the duplicates manually (done)

**Comment by Ralph-Lee-UK** [comment]
many thanks. Again, however, what is displayed on the website doesn't match the text files, at least in the case of scroll EMIPms00474 - will it take a while to update? Sorry for all the questions - I'm trying to work out whether to carry on with the remaining files, or whether there is still an error to correct

**Comment by eu-genia** [comment]
should be ok now

**Comment by Ralph-Lee-UK** [comment]
Many thanks! I'll get on with the others. The XSL is working well mostly now - it is not working well for scrolls with two columns, but I think I will be able to fix that manually!

**Pull request merged**
