### PR TITLE
Emip metadata april 25 2020

### PR DESCRIPTION
**Pull request by Ralph-Lee-UK**
Standard edits to EMIP collection

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
for some reason (the local conflicts discussed per email and the merges from master above?) this PR includes changes to ES* and DSethiop* manuscripts, which clearly do not belong with the EMIP metadata work and should not be part of this PR. Some of them regress from the current status as I could see. I am inclined at the moment to proceed as follows:
- switch to this branch in my local version, 
- save a local copy of the edited EMIP files listed here only (the relevant changes), 
- delete this PR and branch, 
- update master branch to the latest status
- create a new branch from master 
- add there the edited EMIP files from the local copy above 
- and create a new PR and merge it with reference to this PR.
unless somebody has anything to object!

**Comment by Ralph-Lee-UK** [comment]
Pietro. These arose because of mistakes that I made in trying to undo what I had done! I was careful to look at all the minor conflicts that arose here, and it was clear that edits had been done by Denis or others, and I made sure that those were kept, and anything that was introduced in error from my branch was deleted. I think I have worked out a step that I did in error!

**Comment by Ralph-Lee-UK** [comment]
In other words I do not think that there are any problems with the request as it stands. For instance, in one case, Denis had edited files to give better transcriptions, and I kept those, which for some reason were different on my branch. Does that make sense?

**Comment by Ralph-Lee-UK** [comment]
I can do the copying as you suggest if you want to be sure

**Comment by PietroLiuzzo** [comment]
well, if you already know which ones are the files, this would save me some time. let me know when you are done, thanks!

**Comment by PietroLiuzzo** [comment]
I will then review the new PR with the data you copied locally. looking forward to that. thanks again.

**Pull request closed without merging**
