### PR TITLE
Mss for sumschool

### PR DESCRIPTION
**Pull request by eu-genia**
added facs for the MSS that may be used in cataloguing in the school; DSM mss images (DSM-017 and DSM-018) are not yet available on the server

### CODE REVIEW

**Comment by eu-genia** [comment]
sorry did not update on time, you already were doing it, but maybe the others are still useful

**Comment by eu-genia** [comment]
Note there was an error in the facs of DZ-023, here corrected

**Comment by PietroLiuzzo** [comment]
I fail to understand why we are doing this twice. @DenisNosnitsin1970 and @thea-m asked me to do this which I did, and DSM 017 and 018 cannot be done yet, because the tiff images transformation is still running on my computer in the office. 
There was already a merged PR, which everyone should have been notified about, so I am really puzzled about what is going on.

**Comment by PietroLiuzzo** [comment]
also please note https://betamasaheft.eu/Guidelines/?id=images, `n="66"`, not `n="066"`

**Comment by eu-genia** [comment]
then delete the branch, sorry, just note that there was an error in the facs of the DZ ms

**Pull request closed without merging**
