### PR TITLE
Update BLorient765.xml

### PR DESCRIPTION
**Pull request by MarcinKrawczuk**
I have tried to reinstate all the missing data into BLorient765

### CODE REVIEW

**Comment by eu-genia** [comment]
please do the submit into the old branch, or we will get too much confusion

**Comment by MarcinKrawczuk** [comment]
Which branch? The last one I used to modify BLorient765?

**Comment by eu-genia** [comment]
yes, of course, the one where I asked for review https://github.com/BetaMasaheft/Manuscripts/pull/1238

**Comment by eu-genia** [comment]
that one has not been approved or merged yet

**Comment by MarcinKrawczuk** [comment]
OK, done

pon., 1 lis 2021 o 13:45 Eugenia ***@***.***> napisał(a):

**Pull request closed without merging**
