### PR TITLE
Mv bgv09

### PR DESCRIPTION
**Pull request by MassimoVilla**
New PR with the latest changes.

### CODE REVIEW

**Comment by antobrita** [comment]
Massimo, here it is written "this branch has conflicts that must be resolved" and to the right there is the button "Resolve conflicts". Shall I press it? O ignore it?

**Comment by MassimoVilla** [comment]
It is fine, I'll solve the conflicts and update the file to the latest version.

**Comment by antobrita** [comment]
Ok. Then you let me know when it can be merged.

**Comment by MassimoVilla** [comment]
I also was entitled to merge it.

**Comment by antobrita** [comment]
Ok, then you do it.

**Pull request merged**
