### PR TITLE
added codicological information for Bruce 77, correction for Bruce 78

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
If this is not reviewed because of the conflicts :) They are easy to solve, I can do it (and merge) when someone has approved the PR

**Comment by PietroLiuzzo** [comment]
@thea-m please do if you can, thank you.
@DenisNosnitsin1970 @DariaElagina please, if you find difficulties do not hesitate to ask, it is much better to leave things pending around waiting for someone to come across it. Thank you very much

**Comment by thea-m** [comment]
(Is there a way to resolve conflicts without merging?)

**Comment by thea-m** [comment]
image
will this merge or squash and merge? I see no way of changing the setting in the web editor page. @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
AFAIK if you resolve a conflict between master and a branch, in this web editor it will be committed to the branch as a merge of master to the current branch, so it is ok, there is no need to alter that workflow. you proceeded correctly.

**Pull request merged**
