### PR TITLE
Emip metadata 1 october 2020

### PR DESCRIPTION
**Pull request by Ralph-Lee-UK**
in Pietro's absence, can either of you check this (usually just for validation) and approve the pull request?

### CODE REVIEW

**Comment by smaugustine** [comment]
Just to note, when I made my edits and committed them, I hadn't noticed that my local version of the branch was a few hours behind, during which time you had made some commits. This led to a conflict which I've resolved here.

Also, note that @thea-m is also on vacation.

**Comment by Ralph-Lee-UK** [comment]
@smaugustine many thanks. I saw this as I finished work yesterday, and I was planning to sort it out this morning - you have saved me that effort!

**Comment by Ralph-Lee-UK** [comment]
@thea-m or @DenisNosnitsin1970 - are either of you able to approve this, as I said above Pietro usually addresses only validation issues, and we have sorted out the conflict that arose from Augustine's work?

**Comment by DenisNosnitsin1970** [comment]
I can approve to get it merged, but be sure that there is no technical issue etc. and no work will be lost. Should I?

**Comment by Ralph-Lee-UK** [comment]
I have resolved conflicts, so I am confident from our end that no work will be lost.

**Review by DenisNosnitsin1970 — APPROVED** [review]

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 thanks. I have merged the edits. Something has happened that relates to how old the branch was. I see some edits that are preserved on my computer but are not on the master. This has happened because they have been edited since the pull request for the EMIP branch was made. I am now going to check them carefully, and resubmit them on another branch, which I sill submit for approval! Sorry about this, but again be assured that nothing is lost.

**Comment by smaugustine** [comment]
@Ralph-Lee-UK Generally commits to a branch made after the pull request was opened should still go through once it is merged, but sometimes it seems there are hiccups here and there. (It could be a result of commit 183fd8a, in which case, _mea culpa_, I need to be more vigilant about keeping my local copies of branches up to date).

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 and @smaugustine - so I have a message on GitHub following the merge that says 'You have 7 local commits waiting to be pushed to GitHub' - this message appears when the master branch is selected. This has happened to me before, and it has been because of edits on the branch being out of phase (or something like that). I have just carefully looked through all that I can see and I can find no differences - so the work that @smaugustine did on EMIP 480 was flagged, but there is no apparent difference. What I have done in the past when this happened was to make copies and resubmit. I will keep checking all the details, and at the moment I am not deleting the branch that I merged.

**Comment by Ralph-Lee-UK** [comment]
I have found the error and I am confident that nothing has been lost - but I will double check!

**Comment by DenisNosnitsin1970** [comment]
Be sure, I myseld get confused with branches etc. from time to time, and run into small difficulties. So, nothing extraordinary happened :)

**Pull request merged**
