### PR TITLE
added n to idno for images linking

### PR DESCRIPTION
**Pull request by PietroLiuzzo**
added `@n` with total number of newly transformed tiled TIF images stored in server.

Merging this will make accessible all the images newly transformed from Steve hard disk

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
@Ralph-Lee-UK of course you do not need to review a mechanical change to 1400+ files... but I made a PR, so that we can merge it just after your next one, and try in this way to avoid conflicts. you will then create your new branch after both yours and this one have been merged.

**Comment by Ralph-Lee-UK** [comment]
This, I presume, is simply to make sure that we are accessing the most up-to-date images?

**Comment by PietroLiuzzo** [comment]
no, this makes accessible all images and should be merged only after your weekly pr

**Comment by Ralph-Lee-UK** [comment]
I see, so you will do this once the PR is made on Wednesday.

**Comment by PietroLiuzzo** [comment]
i.e. for all these manuscripts anyone on the web will be able to click the images button and see the latest set of images which have been just transformed. the ones already linked (e.g. Tweed) already point to the newest set because there is only one set and it is the latest one which has superseeded the older

**Comment by PietroLiuzzo** [comment]
yes

**Comment by Ralph-Lee-UK** [comment]
Clear! Many thanks

**Pull request merged**
