### PR TITLE
Emip metatdata 13 feb 2020

### PR DESCRIPTION
**Pull request by Ralph-Lee-UK**
Weekly pull request with final edits to some of the Tweed Collection.

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
as I am busy in a workshop, it may take me some time to get to this.

**Comment by Ralph-Lee-UK** [comment]
Pietro, perhaps then I should cancel this pull request, and make another may early next week when you are more available? At the moment we have several instances of people working on the same files, so i think that this would be the best way to avoid conflicts?

**Comment by PietroLiuzzo** [comment]
no, please, just be patient. I will try to get it done at a break

**Comment by Ralph-Lee-UK** [comment]
OK, I'll wait!

**Pull request merged**
