### PR TITLE
Ccrg 30

### PR DESCRIPTION
**Pull request by GueshSol**

### CODE REVIEW

**Review by thea-m — CHANGES_REQUESTED** [review]
Thank you, Guesh, it is great progress! I wrote several comments on the encoding here. I started to correct typos, but then noticed that they were quite many. Could you, in oxygen, use the spelling check and go through the entire file to check for typos?

**Comment by GueshSol** [comment]
Thank you for your crucial comments. I'll correct them accordingly sooner.

**Comment by thea-m** [comment]
Thank you for your patience, Guesh! It is fine now. I carried out a few minor encoding corrections, but they are apparently not coming through on this page. I will wait a bit, and then merge this.

**Comment by GueshSol** [comment]
Okay. Thank you so much!

**Comment by thea-m** [comment]
The corrections I carried out are visible in oxygen, but the commit is not shown here. I will merge to master to see whether they go through.

**Comment by thea-m** [comment]
They went through, it's fine

**Comment by GueshSol** [comment]
Dear Dr. @DenisNosnitsin1970,
One inquiry, I submitted PR concerning my XML description of  MS CCRG01 two months ago. It seems there is a technical problem or it is not approved by one of you (@DenisNosnitsin1970 and @thea-m). Yesterday, I got a notification that the description is merged by Dorothea, but it's not still updated on the online database which is extremely essential for my dissertation.
Thus, can you please check the status of the approval or any suggestions for modification (if any)?
Many thanks,
Guesh

**Comment by thea-m** [comment]
I pushed the file again to master and it is visible now. Only the institution's name is missing in the title, @eu-genia , could you have a look?

**Comment by eu-genia** [comment]
re-expanded, should be ok

**Comment by thea-m** [comment]
It seems fine to me now, thank you!

**Pull request merged**
