### PR TITLE
Update ESmr041.xml

### PR DESCRIPTION
**Pull request by PietroLiuzzo**
https://github.com/BetaMasaheft/Documentation/issues/1694#issuecomment-776734761

### CODE REVIEW

**Review by DenisNosnitsin1970 — COMMENTED** [review]
Sorry, Pietro, I mixed it up, it was ms MR-045.

**Comment by DenisNosnitsin1970** [comment]
Both MR-041 and MR-045 can be made accessible.

**Comment by PietroLiuzzo** [comment]
images of this are loading to the server. it will take sometime but will be available as soon as that happens after this is merged.

**Comment by PietroLiuzzo** [comment]
here is 45, in the issue is 5. I did 5 and 41, should I do also 45?

**Comment by DenisNosnitsin1970** [comment]
Yes, also 45.

**Pull request merged**
