### PR TITLE
added content, additions, binding

### PR DESCRIPTION
**Pull request by thea-m**
I am unsure about assigning the ID LIT1850Malkea, since this manuscript does not follow the typical sequence of hymns of the Malkǝʾa gubāʾe. On the other hand, this is the title given in the ownership note, and we follow the indigenous tradition. What do you think?

### CODE REVIEW

**Comment by thea-m** [comment]
@DenisNosnitsin1970 @DariaElagina

**Comment by eu-genia** [comment]
Could it make sense to have a generic work ID for non-standardized collections of malk that one could refer to here?
This would also be important for our discussion of traditional "labels" vs what we understand under titles of works (then under the MG label you would find everything the tradition may refer to as such, even if it is not THE MG)

**Comment by thea-m** [comment]
I would prefer to keep this open for the moment, instead of maybe too quickly creating the illusion of a standard 
ttps://github.com/BetaMasaheft/Documentation/issues/1381

**Comment by thea-m** [comment]
I'm quite sure that whoever works on https://github.com/BetaMasaheft/Documentation/issues/1381 (which does not seem to happen anytime soon), will find this record then and update it. Can we merge it?

**Pull request merged**
