### PR TITLE
Genbot corrections

### PR DESCRIPTION
**Pull request by thea-m**
@PietroLiuzzo and @Hizkie : There is a schema error in ESqdq004 (which I should have noticed when approving your previous PR, but I hadn't opened the file in oxygen...): 

> The zone element should not be categorized in detail with @subtype unless also categorized in general with @type

I would be great if you could correct this, so that I can work with a valid file and have a better chance at seeing my own errors.

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
I will look at this now.

**Comment by PietroLiuzzo** [comment]
@thea-m in this PR you are pushing your work, so that I can make the corrections you mention before it is merged?

**Comment by thea-m** [comment]
@PietroLiuzzo that was my thought, in case you have time for this now, yes. Thank you! If it takes longer, no trouble!

**Comment by PietroLiuzzo** [comment]
the fix for this was trivial. I am trying to understand from where do those attribute come from.

**Comment by thea-m** [comment]
Great, thank you!

**Comment by PietroLiuzzo** [comment]
They come out of Transkribus. These column labels have been added to image 72, apparently manually, I have not yet understood how. It could be an interesting feature, but at the moment we have to make sure when we copy from there that these are not present. only these two occurrences cropped out so far.

**Comment by PietroLiuzzo** [comment]
should I also squash and merge?

**Comment by thea-m** [comment]
Thanks!

**Pull request merged**
