### PR TITLE
deleted entries

### PR DESCRIPTION
**Pull request by DariaElagina**
Despite renaming of the files (according to the wish of the collectors), previous files were not deleted. This is the second try.

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
I am very curious about what you are trying again. could you instead point me to the first attempt? thanks.

**Comment by PietroLiuzzo** [comment]
I wonder how you can delete something you have already deleted.

**Comment by DariaElagina** [comment]
It was not my branch, here it is: #992

**Comment by PietroLiuzzo** [comment]
As far as I can quickly reconstruct, one branch #992 was merged where the files where renamed on 10.2. . After that  however, a folder /Neukirchen with the old files, was merged #1145 on 18.6. so that they are again there. Probably the now-deleted branch was created before 992 was merged and was not rebased. While the first operation triggered the deletion marking, the following one triggered the 'remove from deleted list' action, so they came back to live. So, it looks to me like the app has been doing its job quite well in terms of responding to the PR merge requests. But let me ask again then: are you 100% sure these should go? If yes I will merge this change, check to be sure that the deletion mark is triggered (you can check this [here](https://betamasaheft.eu/deleted.html)) and we should be fine. One last question from me: is https://github.com/BetaMasaheft/Documentation/issues/1800 related to this?

**Comment by DariaElagina** [comment]
Dear Pietro, thank you! This should go because this has nothing to do with harmonization but with the wish of the owners to stay anonymous. We can not guarantee that if the file name still contains their name. All further changes were done on the "correct" anonymized files.

**Review by PietroLiuzzo — APPROVED** [review]

**Comment by PietroLiuzzo** [comment]
looks to me like all went well, the records are deleted as wished and listed as deleted accordingly. do let me know if you encounter unexpected behaviours.

**Comment by DariaElagina** [comment]
Thank you so much!

**Pull request merged**
