### PR TITLE
EAP336-3 stubs

### PR DESCRIPTION
**Pull request by eu-genia**

### CODE REVIEW

**Comment by eu-genia** [comment]
@MershaMengistie I have been processing images and the image folders once again DO NOT CORRESPOND to the spreadsheet metadata.
E.g. just an example 
Mota Giorgis 004 according to the metadata has 357 folia (Terguame Ebrawuyan); the 004 folder I got from you has 56 images
Mota Giorgis 006 according to the metadata has 120 folia (Terguame Kufale); the 006 folder has 253 images etc etc etc

I cannot work with the data and images if they do not match. We have to have the images numbered EXACTLY as the spreadsheet submitted to EAP.

Thank you for going through all images and all folders and letting me know which FOLDERS must be renumbered, as I have already converted the images and cannot go through all that again. We cannot change the shelfmarks, these remain as they were provided in the spreadsheet.

**Comment by eu-genia** [comment]
In this collection main mismatches are:



MS | TIFFS according to BL spreadsheet | images in folder delivered
-- | -- | --
EAP336_MG004 | 357 | 56
EAP336_MG005 | 140 | 292
EAP336_MG006 | 120 | 253
EAP336_MG008 | 114 | 150

**Comment by thea-m** [comment]
No comments from my side, everything seems fine as long as the mismatching issue is being solved. Thanks a lot!

**Comment by MershaMengistie** [comment]
Zhenia: as you can notice, EAP 336_MG004 is not fully submitted. I am so many folders like c,d,e...are missing in this submission to the center. I don't know if the BL has received the same folders. We have two options: either delete this text or wait until I check the remaining images in my other external driver at home like the Aleqa Mengest collection.

Regarding the number of images in the other folders, i.e. 005, 006 and 008 - we should record what we see i.e. 292, 253 and 150 respectively. There might be a mistake in filling the spreadsheet in 2010.

**Comment by eu-genia** [comment]
Since other metadata submitted to EAP and images match we cannot risk that the images are not of the MS described. Please check carefully the entire metadata in the spreadsheet that everything else matches to the images submitted. The discrepancy is too large

**Comment by MershaMengistie** [comment]
Pity that:

mss from Mamher Walda Iyyasus (EAP336 to MW001-005) are missing in the folder while they are described in the spreadsheet
Instead, there are four undescribed manuscripts in the folder
the remaining five which are described and found in the folder are given different shelfmarks than the one in the spreadsheet:
While 001,2,3,4,5 are missed, what is said (in the spreadsheet) EAP_MW1 should be EAP_MW6; MW3 be MW7; MW4 be MW008; MW6 be MW009; and MW008 be MW010 (in our previous communications this was declared as missing but not). So I should now look for the missing EAP336 to MW001-005. I don't know why this happened :(

**Comment by MershaMengistie** [comment]
The folder EAP336_ML012 should be EAP336_ML011. What is foldered as EAP336_ML011 should be taken out. It was not submitted to the BL since it was not fully digitized. As I see, the rest folders are okay.

**Comment by eu-genia** [comment]
please check Mota Giyorgis 004 and 008

**Comment by MershaMengistie** [comment]
MG004 is not fully submitted. It is cut, as you can see. I am sorry. But MG008 is fine.

**Pull request merged**
