### PR TITLE
DS edits

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Review by DenisNosnitsin1970 — CHANGES_REQUESTED** [review]
We had halaqa Barhe in Ethiop. 7. Can you make him italics? Thanks! :)

**Comment by thea-m** [comment]
Did we have a reason for transliterating ኀለቃ with ḥ, not ḫ?

**Comment by DenisNosnitsin1970** [comment]
I think this way it is transcribed in the manuscript. I remember.

**Comment by thea-m** [comment]
no, it's ኀለቃ

**Comment by DenisNosnitsin1970** [comment]
Stimmt's sein Titel ist nur einmal als ኀለቃ erwähnt.

**Comment by thea-m** [comment]
Genau, also Ḫalaqā?

**Pull request merged**
