### PR TITLE
Create UppEt36.xml

### PR DESCRIPTION
**Pull request by karljonaskarlsson**
Created an empty file to be able to refer to it in the description of O Etiop. 3 – will come back and fill it will content in due time

### CODE REVIEW

**Comment by eu-genia** [comment]
before merging please make sure that the file validates

**Comment by karljonaskarlsson** [comment]
Sorry, could you explain what I need to do to make sure that it validates?

**Comment by eu-genia** [comment]
As far as I can see, you should fill `msItem `with something, at least an empty `<title></title>` tag

**Comment by karljonaskarlsson** [comment]
Thank you! Now I understand!

**Pull request merged**
