### PR TITLE
Add BAVet 208 and update MSS with Lessana Sab'/Evil Eye on Tiberias

### PR DESCRIPTION
**Pull request by smaugustine**
These manuscripts contain ChRep314 (Lessana Sab') and also the story of Jesus and his disciples encountering the evil eye on the Lake of Tiberias.

This pull request adds BAV et 208, which contains both, and updates the other MSS to properly reference the relevant work IDs.

### CODE REVIEW

**Review by eu-genia — APPROVED** [review]

**Comment by smaugustine** [comment]
@PietroLiuzzo, [this commit (8efd8a61b)](https://github.com/BetaMasaheft/Manuscripts/pull/757/commits/8efd8a61b017dc87139589af9aad18b8bcda896e) should have removed BAVet208.xml from the new folder, but it seems to still be in the repo, and I'm not sure why?

**Comment by PietroLiuzzo** [comment]
it did but it did not delete it from the previous location on the app, I will have to look at your permissions, which I cannot do right now, will do in a couple of hours

**Comment by PietroLiuzzo** [comment]
I have hand fixed it for the time being http://betamasaheft.eu/BAVet208

**Comment by PietroLiuzzo** [comment]
please delete merged branches

**Pull request merged**
