### PR TITLE
DSEthiop22

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
Some changes

### CODE REVIEW

**Comment by thea-m** [comment]
I've deleted MS DSEthiop120, which is exactly identical with DSEthiop12, and was probably created by accident.

**Comment by DenisNosnitsin1970** [comment]
Thanks!
I have no idea how Ethiop 120 came to be. Was it me? :)

**Comment by thea-m** [comment]
I think it was your unconscious wishing for 120 more manuscripts

**Comment by DenisNosnitsin1970** [comment]
:)

**Comment by DenisNosnitsin1970** [comment]
Maybe, they will come! :)

**Pull request merged**
