### PR TITLE
Munich7

### PR DESCRIPTION
**Pull request by vitagrazia81**
The last record I have created for the Munich collection.
P.S. I am sorry, I bombarded you with all these pull requests. Forgive me, especially if you are not working or if you are busy with somethings else!
Many thanks in advance!
Vita

### CODE REVIEW

**Comment by thea-m** [comment]
Dear Vita, thank you! I believe you moved all your previous changes to the new branches you created (or something similar), so that now each PR shows the same changes. That is no problem, I just wanted to let you know, so that you can check this in the future when you will create new pull requests.
Everything seems fine to me (I see that the space has been corrected), but there is now one small conflict that needs to be solved before this can be merged. It is not complicated, you can do it yourself: Below "This branch has conflicts that must be resolved", click on "use the web editor". You will then see the conflict highlighted: 
image

Choose the correct version and delete the other one. Also delete "<<<<<<< Munich7, =======, >>>>>>> master". Then, everything should be fine and you can click on "mark as resolved" on the top of the page, and then on "commit merge". Then the conflict will be resolved and I will merge this PR. 
Let me know if this is unclear or any problems come up!
Thank you!

**Comment by vitagrazia81** [comment]
Thank you Dorothea. I think I did now. I hope so :-)

**Review by thea-m — APPROVED** [review]

**Comment by thea-m** [comment]
Thank you!
On the separation of descriptions based on catalogues and consultation of the manuscripts, there is an ongoing discussion, not yet resolved: https://github.com/BetaMasaheft/Documentation/issues/1844
Considering the current state of the records, I think it isn't particularly relevant yet. In the future, the most important thing will be to clearly state in change elements (in more details than you can find in existing files!) which information is based on what. And when you continue the encoding of these records, you will be able to chose the best option.
(There is nothing that needs to be done after the branch has been merged.)

**Comment by vitagrazia81** [comment]
Dorothea, good to know that there  is on ongoing discussion and an issue.
Thanks again for your review.

I created big confusion with the creation with all these branches before I did the pull requests. I am sorry, I thought I needed to do  for each ms encoded. They are 7, but  when I open Atom I don't see all of them.

**Comment by gnizla** [comment]
Thanks @thea-m I feel like we need to find ways to credit your contribution that go beyond a mere acknowledgement but that add a more permanent type of record in BM and/or in published format.

**Pull request merged**
