### PR TITLE
colophon try, once again

### PR DESCRIPTION
**Pull request by thea-m**
This will hopefully correct the script size

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
mmm... do you need help?

**Comment by thea-m** [comment]
If this makes the English script appear as that of main text, no, otherwise, yes!

**Comment by PietroLiuzzo** [comment]
this remains highly cryptic to me, sorry. if this change in `@xml:lang` is made for the printed catalogue, changing from `gez` to `ti` will have no visible effect, because the settings are the same for both languages, i.e. `letter-spacing = '0.5pt'  font-size ='0.9em'`. Removing as you did one or the other (which, btw, looks to me to be more correct encoding in any case) will default on Ludolfus without further specifications. If this is what you wanted to achieve you are all set!

**Review by DenisNosnitsin1970 — APPROVED** [review]

**Comment by thea-m** [comment]
That is what we wanted and what we have achieved.

**Pull request merged**
