### PR TITLE
QDSM stubs

### PR DESCRIPTION
**Pull request by eu-genia**
https://github.com/BetaMasaheft/Documentation/issues/713

### CODE REVIEW

**Comment by eu-genia** [comment]
Dear Mersha, 

I have created the provisional stubs BUT before these can be merged please check whether any of the MSS have already been microfilmed and/or digizied by EMML. Since we already have records for all EMML mss we cannot create new records for the manuscripts we already have (I can add images and your metadata to existing records). 

Please check the catalogue and the virtual reading room and mark the correspondences.

I strongly assume that your QDSM003 is actually EMML521 and QDSM006 is actually EMML526 but also others must be carefully checked.

Images at least for EMML 504, 505, 508, 509, 510, 511, 513, 514, 515, 517, 520, 522, 524, 526, 543, 544, 545, 547, 548, 552 are online, more are in [William F. Macomber, A Catalogue of Ethiopian Manuscripts Microfilmed for the Ethiopian Manuscript Microfilm Library, Addis Ababa, and for the Hill Monastic Manuscript Library, Collegeville, vol. II: Project Numbers 301-700 (1976)](https://archive.org/details/EMMLCatalog02)
NB 509, 512 is a Deggwa - both 20th century, there is no MS listed dating to the 15th - are you sure your QDSM001 dates to the 15th century? What is the basis for this assumption?

Thank you.

**Comment by eu-genia** [comment]
EMML526
image

**Comment by eu-genia** [comment]
EMML525
image

**Comment by eu-genia** [comment]
EMML521
image

**Comment by eu-genia** [comment]
EMML509
image

could be QDSM001

**Comment by eu-genia** [comment]
EMML512
image

**Comment by eu-genia** [comment]
EMML517 looks like QDSM004
image

**Comment by eu-genia** [comment]
EMML518
image

**Comment by eu-genia** [comment]
EMML523 could be QDSM002
image

**Comment by MershaMengistie** [comment]
Thank you, Zhenia. Yes, that might be true as QDSM was obviously one of the churches in Addis Ababa that was microfilmed by the EMML. I will definitely check. But we don't have DSQM006 though.

**Comment by eu-genia** [comment]
In your spreadsheet you have QDSM006 which is a Zemmare, the description looks the same as that of EMML525 , see above

**Comment by MershaMengistie** [comment]
Yes yes, thank you...I only referred to the scientific report. Sure they are six mss. I will compare them with the EMML.

**Comment by eu-genia** [comment]
Email from @MershaMengistie : Good morning Zhenia. There is a strong tendency that all the six mss from QDSM are microfilmed. I don't know why, but they locked my account so that I cannot correspond with the images at vhmml. I asked them to unlock me.

But looking into the catalogue, it seems that QDSM001 is EMML 512; QDMS002 is EMML 523; QDSM003 is EMML 521; QDSM004 is EMML 517; QDSM006 is EMML 525. Couldn't identify QDMS005.

**Comment by eu-genia** [comment]
Dear @MershaMengistie  thank you but I am not sure QDSM001 is EMML512, please check the short description at https://betamasaheft.eu/manuscripts/EMML512/main, the notes and the name of the scribe do not match

**Comment by thea-m** [comment]
(Approval pending the final identification check, was too quick :) )

**Comment by eu-genia** [comment]
003 and 006 are fixed, I will wait for the images before checking the others, the identification of 001 002 and 004 is not 100%

**Comment by MershaMengistie** [comment]
> r

I assume I rightly corresponded 001 and 002 with the project numbers EMML 512 and 523 respectively. I followed what has been described like stamps and other short notes checking their appearance on the stated folios. But I will relook them tomorrow.

**Review by MershaMengistie — APPROVED** [review]

**Comment by eu-genia** [comment]
I did not see the images but the spreadsheet says for
QDSM001 Scribe: ዘአባ ደስታ (should be of course አባ ደስታ), col. f. 167, mentions also other names
EMML512 has scribe: Gabra Heywat (colophon, f. 90a) and a note that it was sold by Qes Yemar (the same as Gabra Heywat?) to Aggafari Getahun, acting on behalf of Ato Bassa, who was buying the manuscript for the Church of the Savior of the World

**Comment by MershaMengistie** [comment]
Aha...good observation. I will check tomorrow as the external drive is not with me now. 
    Am Freitag, 5. Mai 2023 um 19:18:50 MESZ hat Eugenia ***@***.***> Folgendes geschrieben:  
 
 


I did not see the images but the spreadsheet says for
QDSM001 Scribe: ዘአባ ደስታ (should be of course አባ ደስታ), col. f. 167, mentions also other names
EMML512 has scribe: Gabra Heywat (colophon, f. 90a) and a note that it was sold by Qes Yemar (the same as Gabra Heywat?) to Aggafari Getahun, acting on behalf of Ato Bassa, who was buying the manuscript for the Church of the Savior of the World

**Comment by eu-genia** [comment]
QDSM002 has 2 columns, EMML523 has 3 columns

**Comment by MershaMengistie** [comment]
Aha...;)

Sent from Yahoo Mail on Android 
 
  On Fri, 5 May 2023 at 19:30, ***@***.***> wrote:   


QDSM002 has 2 columns, EMML523 has 3 columns

**Pull request merged**
