### PR TITLE
Update HNK-001.xml

### PR DESCRIPTION
**Pull request by eu-genia**

### CODE REVIEW

**Comment by MershaMengistie** [comment]
Excellent

**Comment by eu-genia** [comment]
do the approve (add review - approve)

**Review by MershaMengistie — APPROVED** [review]

**Comment by MershaMengistie** [comment]
Done!
    Am Mittwoch, 6. April 2022, 22:07:16 MESZ hat Eugenia ***@***.***> Folgendes geschrieben:  
 
 


do the approve (add review - approve)

**Comment by eu-genia** [comment]
thank you, perfect!

**Pull request merged**
