### PR TITLE
BL shelfmarks

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Review by DenisNosnitsin1970 — CHANGES_REQUESTED** [review]
As far as I see, you left "Add." as it was. Didn't you intend to write it out?

**Comment by eu-genia** [comment]
> As far as I see, you left "Add." as it was. Didn't you intend to write it out?

they are written out in a later commit. I was wondering about the commas in Additional numbers - first inserted then removed - do we agree on commas out?

**Comment by DenisNosnitsin1970** [comment]
Commas inside can be dropped.

**Review by eu-genia — APPROVED** [review]

**Comment by thea-m** [comment]
@DenisNosnitsin1970 , is it alright for you? If not, please note it here or in the accompanying issue. Thanks!

**Pull request merged**
