### PR TITLE
corrected ል to ፡

### PR DESCRIPTION
**Pull request by thea-m**
I am relatively sure it is a typo

### CODE REVIEW

**Comment by nafisa-valieva** [comment]
yes, thank you for your correction, Dorothea!

**Comment by thea-m** [comment]
Could I trouble you to follow the official workflow? It might be a good practice. Could you approve the change, then I can merge. Now, as long as it is not merged, it is not corrected in the master branch.

**Comment by nafisa-valieva** [comment]
I am sorry, I am reviewing for the first time! I approve your correction.

**Comment by thea-m** [comment]
I am honoured!

**Pull request merged**
