### PR TITLE
EAP336-5 stubs

### PR DESCRIPTION
**Pull request by eu-genia**

### CODE REVIEW

**Review by MershaMengistie — APPROVED** [review]
My previous comment is copied here.

**Comment by eu-genia** [comment]
Here too we have obvious metadata discrepancy, the shelfmarks and the image folders do not match (actually all folders marked as Mamher Wolde Iyasus collection seem to be of different mss)


MS | TIFF according to BL spreadsheet | Images in the folder
-- | -- | --
Mamher Solomon EAP336_MS005 | 40 | 294
Mamher Solomon EAP336_MS006 | 58 | 54
Mamher Wolde Iyasus EAP336_MW002 | 129 | 338
Mamher Wolde Iyasus EAP336_MW003 | 151 | 371
Mamher Wolde Iyasus EAP336_MW004 | 242 | 138
Mamher Wolde Iyasus EAP336_MW005 | 172 | 126
Mamher Wolde Iyasus EAP336_MW006 | 154 | 104
Mamher Wolde Iyasus EAP336_MW007 | 366 | 54
Mamher Wolde Iyasus EAP336_MW008 | 131 | 450
Mamher Wolde Iyasus EAP336_MW009 | 98 | 29

**Comment by eu-genia** [comment]
@MershaMengistie writes: While 001,2,3,4,5 are missed, what is said (in the spreadsheet) EAP_MW1 should be EAP_MW6; MW3 be MW7; MW4 be MW008; MW6 be MW009; and MW008 be MW010 

So MWI updated table is
MS | TIFF according to BL spreadsheet | Images in the folder
-- | -- | --
Mamher Wolde Iyasus EAP336_MW006 | 154 | 161 OK !
Mamher Wolde Iyasus EAP336_MW007 | 366 | 371 OK !
Mamher Wolde Iyasus EAP336_MW008 | 131 | 138 OK !
Mamher Wolde Iyasus EAP336_MW009 | 98 | 104 OK !
Mamher Wolde Iyasus EAP336_MW010 | 469 | 450 to re-check as usually there should be more images than folia

**Comment by eu-genia** [comment]
And - do we know which collection the images currently submitted as Mamher Wolde Iyasus 002, 003, 005 and 009 belong to?

**Pull request merged**
