### PR TITLE
BLadd19342

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
Yes, I don't know about it's origin...I wonder whether the "pontificale" means that the church in question was one regularly visited by the pope - or do all churches have such pontificial clothes?...

**Comment by DenisNosnitsin1970** [comment]
No one knows, one has to see the manuscript.

**Comment by thea-m** [comment]
you can :) http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_19342_fs001r 
but it did not help me much

**Comment by DenisNosnitsin1970** [comment]
Mysterious object! It should be left for future generations. :)

**Pull request merged**
