### PR TITLE
Update DSEthiop4.xml

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
Minor correction.

### CODE REVIEW

**Comment by DenisNosnitsin1970** [comment]
Small correction.

**Comment by thea-m** [comment]
I can only see changes in layout, can you give me a tip where in the record your correction is?

**Comment by DenisNosnitsin1970** [comment]
h1 under "Hands" was missing, only that (but the file was reporting a mistake). Could have merged it by myself.

**Comment by thea-m** [comment]
I see in the file
```xml
    <handNote xml:id="h1" script="Ethiopic">
                        <date notBefore="1850" notAfter="1951"/>
                        <!--<desc></desc>-->
                        <seg type="ink">Black, red.</seg>
                     </handNote>
```
Is this what you mean?

**Comment by DenisNosnitsin1970** [comment]
Yes.

**Pull request merged**
