### PR TITLE
Delete ESmy027.xml

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
Entry deleted (a few changes of sigratures in MY collection).

### CODE REVIEW

**Comment by eu-genia** [comment]
if you change signatures of remaining manuscripts this must be clearly documented as there are also images to rename then

**Comment by eu-genia** [comment]
it would be better not to change signatures, since these may be also documented in publications (including yours)

**Comment by DenisNosnitsin1970** [comment]
Please merge.

**Comment by eu-genia** [comment]
please make an issue with a list of changes/deletions in E-S shelfmarks, referring to this PR, this must be duly documented

**Comment by DenisNosnitsin1970** [comment]
Sorry I confused, this deletion is not related to signature change, it is a mistaken record that should be removed (there will be a change elsewhere in MY, and I will open the issue, but it is a small-scale one, so no worries indeed).

**Review by eu-genia — APPROVED** [review]

**Pull request merged**
