### PR TITLE
EMIP Metadata

### PR DESCRIPTION
**Pull request by Ralph-Lee-UK**
Recommitted files to address problems with today's pull request

### CODE REVIEW

**Comment by Ralph-Lee-UK** [comment]
This is the replacement pull request for the EMIP metadata edits for this week.

**Comment by Ralph-Lee-UK** [comment]
I haven't deleted the other branch, but we can do that once this is completed.

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Manuscripts/pull/387

**Comment by PietroLiuzzo** [comment]
there are some files which only have a `<change>` but not the described change. was that already in a previous branch and PR?

**Comment by Ralph-Lee-UK** [comment]
Can you point me to an example?

**Comment by PietroLiuzzo** [comment]
the second file in the files changed view for me is EMIP000037, where it looks like only a change element was subsituted

**Comment by Ralph-Lee-UK** [comment]
Yes! This is where the conflict was that I had anticipated. The change to the code that I did and that Thea did was identical, as it only involved the substitution of the code for the work, replacing a work file that has been deleted. So I am confident that in these cases that this is correct, and that nothing has been lost.

**Comment by PietroLiuzzo** [comment]
then dorothea's change should not be removed from the list of changes, please

**Comment by Ralph-Lee-UK** [comment]
I think I have completed this. I have deleted my change statement where it described exactly the same thing that Dorothea had done.

**Pull request merged**
