### PR TITLE
Emip 1953 corrections

### PR DESCRIPTION
**Pull request by smaugustine**
_Lǝfāfa ṣǝdq_ begins earlier than was previously indicated and the subdivisions of the text were not totally according to those in the work file (which follows Euringer's edition).

I would change some of the titles of the subdivisions, but I tried to keep my changes to a minimum.

As per [this issue](https://github.com/BetaMasaheft/Documentation/issues/1501), work record(s) for _Zenā ḥǝmāmātihu la-Krǝstos_ (which is item 2.9 here) need to be created, but I/we are still (?) sorting that out.

### CODE REVIEW

**Comment by Ralph-Lee-UK** [comment]
Check with @thea-m, but which recension of the text is in this ms? 

Regarding the changes, your work is much appreciated. The original entry is made from a set of data from a catalogue. Most of the entries are good, but there will be errors, so please don't worry - if you think you can improve the record further, then please go ahead!

**Review by Ralph-Lee-UK — APPROVED** [review]
Many thanks - this is a huge improvement on the original record.

**Comment by smaugustine** [comment]
You mean which recension from the two described by Euringer? I don't think the work record distinguishes this, nor have I checked the manuscript.

There is a real need for further, more extensive study of the manuscript tradition for ልፋፈ፡ ጽድቅ፡ — something I started ages ago (which is why I noticed this record) and may not ever be able to complete (given the sheer number of MSS and variations).

**Comment by Ralph-Lee-UK** [comment]
@smaugustine I'm with you - each time I enter data, I feel that I am laying the ground for about 50 PhDs! 

As we don't know the details of the recension, should we not use the general entry LIT5020Hemamatihu for this ms?

**Comment by smaugustine** [comment]
@Ralph-Lee-UK Ahh, sorry, the recension for Zenā Hǝmāmātihu. It's the shorter recension, which is the one found in virtually every manuscript. The only real exception, to my knowledge, is the one Piovanelli mentions, but I suspect that there may be some more.

I can do some comparisons of manuscripts and see if they all fall into the short recension (and that LIT5020Hemamatihu is enough).

**Pull request merged**
