### PR TITLE
PDF edits

### PR DESCRIPTION
**Pull request by thea-m**
I am working on the example PDF. Here are some edits related to the output in our example files e30, c14 and d20.

- I have not been able to edit the script to print the content of elements `<term>` and `<ref>`, so spelled it out manually: please check that my choices of words and capitalisation are as you want, @gnizla  and @ElianaDalSasso .
- added parantheses around bibliographic references
- corrected missing # in `<locus>` (also in other files)

Thanks!

### CODE REVIEW

**Comment by gnizla** [comment]
Thanks @thea-m just to be clear, there is no way for us to preview this PDF through Git, am I right?

**Review by ElianaDalSasso — APPROVED** [review]
Dear Thea, thank you! For me the capitalisation is fine! in the next binding desc I will spell out the elements.

**Comment by thea-m** [comment]
@gnizla No, unfortunately that's not possible. We can produce (and experiment with) the PDF only in Oxygen (as far as I'm aware of). The set-up is easy, let me know if you want to try it out.

**Review by gnizla — COMMENTED** [review]
Thanks, I just did a minor tweak

**Review by MassimoVilla — APPROVED** [review]

**Pull request merged**
