### PR TITLE
Stubs for Gadla Sadqan zaBaraknaha MSS

### PR DESCRIPTION
**Pull request by eu-genia**

### CODE REVIEW

**Comment by DariaElagina** [comment]
Sorry, I do know the background, what are the records BaraknahaSadqan and BaraknahaSadqan2 stay for?

**Comment by eu-genia** [comment]
manuscripts kept (one not any more) in the church of Baraknaha in Eritrea, containing the Lives of the Righteous Ones

**Comment by thea-m** [comment]
Does the text bibliography here also refer to text of these manuscripts printed which does not constitute an edition?

**Review by thea-m — APPROVED** [review]

**Comment by DariaElagina** [comment]
Just to be sure, the repository refers to PRS12530SadeqanBaraknaha. Is that correct?

**Comment by eu-genia** [comment]
thank you

**Pull request merged**
