### PR TITLE
Emip metadata tweed scrolls 26 september 2022

### PR DESCRIPTION
**Pull request by Ralph-Lee-UK**
@eu-genia here is another set of edits for the EMIP Tweed Scrolls project. There are many files, but for each one (apart from one spelling correction to the transkribusText file for EMIPms00477) the same operations have been done:

1) create directory with record name
2) move original record file to directory
3) add facsimile and transkribusText files to directory
4) add include code at the end of record to include facsimile and transkcribusText file. 

There are no errors in Oxygen for each of these - but if you find an error in one then just bounce it back to me, as the same error will be present in each one.

### CODE REVIEW

**Comment by Ralph-Lee-UK** [comment]
@eu-genia Let me check the validation errors before proceeding

**Comment by Ralph-Lee-UK** [comment]
@eu-genia Validation errors now corrected.

**Review by eu-genia — APPROVED** [review]
thank you

**Comment by eu-genia** [comment]
for the future, please, make sure that there are no more than 20 (better fewer) files per pull request. i will have to upload the files manually again, as they are far too many to be dealt with by the automatic syncing script. thank you very much.

**Comment by Ralph-Lee-UK** [comment]
Will do.

**Pull request merged**
