### PR TITLE
Lessana Sab' MSS

### PR DESCRIPTION
**Pull request by smaugustine**
Add BAVet 208

### CODE REVIEW

**Comment by smaugustine** [comment]
I just noticed that some of the commits got mixed up so that it includes 116 and 117 (this pull request is only to add 208). I will see what I can do about this.

**Comment by PietroLiuzzo** [comment]
in theory if you create your new branch from master, you should not have those changes which are part of vatican-manuscript branch, or is that not so?

**Comment by smaugustine** [comment]
@PietroLiuzzo That's what I expected, but that doesn't seem to be the case in practice. I even tried to make a new branch from master using VSCode instead of Atom -- specifying clearly that it was new from master -- but the commits from the open pull request on the other branch persist.

I've now tried three times and each branch ends up with at least three files changed (116, 117, and 208).

**Comment by PietroLiuzzo** [comment]
what I do usually is to commit what is uncommitted to the branch where I am working, switch back to master, then make a branch from there.  I use Github Desktop, which asks you and warns you if for example you have uncommitted changes which will then have to be brought to the new branch not to get lost. I do not know VSCode, sorry!

**Comment by eu-genia** [comment]
Augustine - when you have multiple branches and you do not want to move changes around (indeed, what you describe is the normal behaviour) you should always go via master branch.
that is - you have the 116-117 branch, you have committed all changes there. even if they are not yet merged yet - if you are not now continuing your work on them you have to go to master, and create the 208 branch from there, then it would have only 208 in it

**Comment by eu-genia** [comment]
(when you switch to master you should of course pull from master, then your local changes in 116 117 would be overwritten, so they will "disappear")

**Comment by smaugustine** [comment]
The issue, it turned out, was that there were some commits that had crept in due to Atom messing up pull requests from master (sounds odd, I know, but something strange happened), and so the commits were actually from master, not from another branch, which is why they were copied over. In the end I simply deleted my local copy and did a fresh clone to remove the commits and make a clean branch from master.

**Comment by smaugustine** [comment]
Suffice to say, Atom is not my Git app of choice (nor even my editor of choice, but I still haven't succeeded in adding TEI linting/validating to VS Code). Giving in and using GitHub Desktop has helped avoid these issues (though, of course, GitHub also makes Atom...).

**Pull request closed without merging**
