### PR TITLE
Bruce 82

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by DenisNosnitsin1970** [comment]
"The edges of the manuscript have been cut off before binding and gilded" - do you mean the that the textblock was trimmed, and its edges were gilded?
"One paper fly leaf each, containing a watermark with a pattern and Latin characters at the front and a watermark with Latin characters at the back". - Not very clear, what is "pattern"?

**Comment by thea-m** [comment]
"do you mean the that the textblock was trimmed, and its edges were gilded?" Yes, much better, thank you! I will correct the other records as well.
Then maybe it would be better to just state the presence of the watermark without attempts of description?

**Comment by DenisNosnitsin1970** [comment]
Just state the presence of a watermark, that will be fine.

**Comment by thea-m** [comment]
It this ok now?

**Comment by thea-m** [comment]
I think that the structure of the last quire was unclear to me, and the reason from the stub not obvious.

**Pull request merged**
